#!/usr/bin/env python3

import os
import sys
import re
from shutil import copyfile
import nbformat
from nbconvert import HTMLExporter
from nbconvert.preprocessors import ExecutePreprocessor
from datetime import datetime


def get_monitoring_notebook_template_path():
    path = os.path.join(
        settings.REPO_DIR, 'backend', 'monitoring', 'notebooks',
        'monitoring_template.ipynb')
    return path


def get_monitoring_notebook_output_path(datestamp, ext='ipynb'):
    notebook_name = 'monitoring_{datestamp}.{ext}'.format(
        datestamp=datestamp, ext=ext)
    path = os.path.join(settings.EXPORTS_DIR, notebook_name)
    return path


def run_notebook(notebook):
    # See http://nbconvert.readthedocs.io/en/latest/execute_api.html
    # TODO: Specify 'django_extensions' kernel and make it work on the server.
    # The kernel can be set as follows:
    #   ep = ExecutePreprocessor(timeout=120, kernel_name='django_extensions')
    # This works locally, but on server, I wasn't able to create the kernel
    # (list available kernels by `jupyter kernelspec list`).
    # Default kernel currently works, given the `path` (directory from where to
    # execute the notebook) is set to //backend. It may fail if some Django
    # features are used in the notebook, but I haven't explored this.
    ep = ExecutePreprocessor(timeout=120)
    #path = os.path.join(settings.REPO_DIR, 'backend')
    #ep.preprocess(notebook, {'metadata': {'path': path}})
    ep.preprocess(notebook, {})


def export_notebook_to_html(notebook, output_path):
    html_exporter = HTMLExporter()
    html, _resources = html_exporter.from_notebook_node(notebook)
    with open(output_path, 'wt') as outfile:
        outfile.write(html)


if __name__ == '__main__':
    if len(sys.argv) < 3:
        sys.stderr.write('Usage: export_monitoring_notebook notebook output\n')
        sys.exit(1)

    template_path, output_path = sys.argv[1:3]
    with open(template_path) as infile:
        notebook = nbformat.read(infile, as_version=nbformat.NO_CONVERT)
    run_notebook(notebook)
    export_notebook_to_html(notebook, output_path)
